import { createClient } from 'npm:@supabase/supabase-js@2.42.0'
import { sendEmail } from './mail.ts'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

function formatExpiryInPrague(expiresAt: Date): string {
  return new Intl.DateTimeFormat('cs-CZ', {
    timeZone: 'Europe/Prague',
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  }).format(expiresAt)
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: req.headers.get('Authorization')! } } }
    )

    // 1. Get the user from the authorization header
    const {
      data: { user },
      error: userError,
    } = await supabaseClient.auth.getUser()

    if (userError || !user) {
      throw new Error('Unauthorized')
    }

    // 2. Check if the user is an admin by querying public.user_roles
    const { data: userRole, error: roleError } = await supabaseClient
      .from('user_roles')
      .select('role')
      .eq('user_id', user.id)
      .single()

    if (roleError || userRole?.role !== 'admin') {
      throw new Error('Forbidden: Only admins can invite users')
    }

    // 3. Admin verified. Now use Service Role to perform the invite action.
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    const { email, role = 'editor' } = await req.json()

    if (!email) {
      throw new Error('Email is required')
    }

    // Check if user already exists
    const { data, error: listError } = await supabaseAdmin.auth.admin.listUsers()
    if (listError) throw listError

    let emailType = 'invite';
    const existingUser = data.users.find(u => u.email?.toLowerCase() === email.toLowerCase())
    if (existingUser) {
        if (existingUser.email_confirmed_at) {
            console.log('User already active, sending password reset link:', email)
            emailType = 'recovery';
        } else {
            console.log('User exists but not confirmed. Resending invite...')
            // Proceed to generate link for existing user
        }
    }

    // Determine redirect URL based on request origin
    const origin = req.headers.get('origin') || req.headers.get('referer');
    let siteUrl = 'https://akhcr.cz';
    
    if (origin && (origin.includes('localhost') || origin.includes('127.0.0.1'))) {
        siteUrl = origin.replace(/\/$/, ''); // Remove trailing slash
        console.log(`Detected local environment, setting siteUrl to: ${siteUrl}`);
    } else {
        console.log(`Using production siteUrl: ${siteUrl}`);
    }

    const redirectTo = `${siteUrl}/auth/v`; 
    console.log(`Redirect To: ${redirectTo}`);
    
    // 4. Generate Link
    console.log(`Generating ${emailType} link for ${email}...`)
    const { data: linkData, error: linkError } = await supabaseAdmin.auth.admin.generateLink({
        type: emailType as any,
        email: email,
        options: {
            redirectTo: redirectTo
        }
    })

    if (linkError) throw linkError

    let inviteLink = linkData.properties.action_link
    console.log(`Original Link: ${inviteLink}`)

    // If the link generated by Supabase (which relies on its own CONFIG) points to localhost
    // but we are in production (siteUrl is akhcr.cz), we might want to patch it.
    // However, if we trust 'redirectTo' to work, Supabase should handle the final hop.
    // The link user clicks -> Supabase -> redirectTo.
    
    // Check if the link itself looks wrong (e.g. localhost when we want production)
    // AND we are NOT in a local environment.
    const isLocalEnv = siteUrl.includes('localhost') || siteUrl.includes('127.0.0.1');
    if (inviteLink.includes('localhost') && !isLocalEnv) {
         console.warn('Patched localhost base URL in invite link to production');
         // Robustly replace http://localhost:PORT or https://localhost:PORT with siteUrl
         inviteLink = inviteLink.replace(/https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?/, siteUrl);
         
         // Also try to fix encoded params if they leaked
         // We do this by parsing the url, fixing the redirect_to param if exists
         try {
            const urlObj = new URL(inviteLink);
            const redirectToParam = urlObj.searchParams.get('redirect_to');
            if (redirectToParam && (redirectToParam.includes('localhost') || redirectToParam.includes('127.0.0.1'))) {
                urlObj.searchParams.set('redirect_to', redirectTo);
                inviteLink = urlObj.toString();
            }
         } catch (e) {
             console.error('Failed to parse/patch url params:', e);
         }
    }
    
    console.log(`Final Link: ${inviteLink}`)
    console.log(`Link generated. Sending via Nodemailer (Port 465)...`)

    // 5. Send Email via mail.ts
    const isRecovery = emailType === 'recovery';
    const subject = isRecovery ? 'Obnova přístupu do administrace AKH webu' : 'Pozvánka do administrace AKH webu';
    const title = isRecovery ? 'Obnova přístupu' : 'Byli jste pozváni do administrace AKH webu';
    const buttonText = isRecovery ? 'Obnovit heslo' : 'Přijmout pozvánku';

    const inviteLinkExpirySeconds = Number(Deno.env.get('INVITE_LINK_EXPIRY_SECONDS') ?? '86400');
    const safeInviteLinkExpirySeconds = Number.isFinite(inviteLinkExpirySeconds) && inviteLinkExpirySeconds > 0
      ? inviteLinkExpirySeconds
      : 86400;
    const expiresAt = new Date(Date.now() + safeInviteLinkExpirySeconds * 1000);
    const expiresAtLabel = formatExpiryInPrague(expiresAt);

    const htmlContent = `
            <h2>${title}</h2>
            <p>Kliknutím na odkaz níže ${isRecovery ? 'obnovíte své heslo' : 'přijmete pozvánku a nastavíte si heslo'}:</p>
            <p><a href="${inviteLink}">${buttonText}</a></p>
            <p>Nebo zkopírujte tento odkaz do prohlížeče:</p>
            <p>${inviteLink}</p>
            <p><strong>Odkaz je platný do ${expiresAtLabel} (Europe/Prague).</strong></p>
            <p><small>Cíl odkazu: ${redirectTo}</small></p>
        `;

    await sendEmail({
        to: email,
        subject: subject,
        html: htmlContent
    });

    // 6. Assign the role in public.user_roles (User is created by generateLink)
    const { error: insertError } = await supabaseAdmin
      .from('user_roles')
      .insert({ user_id: linkData.user.id, role: role })

    if (insertError) {
        if (insertError.code === '23505') {
            console.log('User already has this role, ignoring duplicate key error.');
        } else {
             console.error('Failed to assign role:', insertError);
             throw insertError;
        }
    }

    return new Response(
      JSON.stringify({ success: true, message: `Uživatel ${email} byl pozván jako ${role}` }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    )

  } catch (error: any) {
    console.error('Invite error:', error)
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 400,
    })
  }
})
